config/routes.rb
Liquididea::Application.routes.draw do

  get 'calaview' => 'calaview#index'

end

app/models/calagator_events.rb
require 'open-uri'
#require 'json'

class CalagatorEvents
  def initialize
    @source_uri = "http://calagator.org/events.json"
  end

  def events
    JSON.parse(open(@source_uri).read)
  end

  def ranked_events(weighting_hash)
    @events = events#[0..10]

    @events.each do |event|
      rank, why = event_rank(event, weighting_hash)
      event["why_rank"] = why if why.present?
      event["weighted_rank"] = rank
    end

    @events.sort! { |a, b| b["weighted_rank"]<=>a["weighted_rank"] }
  end

  def rank_from_weight (weight)
    weight
  end

  def time_before(time1, time2)
    time1 = DateTime.parse(time1) unless time1.is_a? DateTime
    time2 = DateTime.parse(time2) unless time2.is_a? DateTime
    time1.seconds_since_midnight < time2.seconds_since_midnight
  end

  def time_match(event, rule)
    match=true
    if rule["time"].present?
      if rule["time"]["starts_after"].present?
        match=false if time_before(event["start_time"], rule["time"]["starts_after"])
      end
      if rule["time"]["starts_before"].present?
        match=false if time_after(event["start_time"], rule["time"]["starts_before"])
      end
      if rule["time"]["ends_after"].present?
        match=false if time_before(event["end_time"], rule["time"]["ends_after"])
      end
      if rule["time"]["ends_before"].present?
        match=false if time_after(event["end_time"], rule["time"]["ends_before"])
      end    end
    match
  end

  def event_rank(event, weighting_hash)
    rules = [
      {"text" => "ruby", "weight" => 2},
      {"text" => "robot", "weight" => 3},
      {"where" => "new relic", "weight" => 1},
      {"when" => {"time" => {"starts_after" => "8:00pm"}},
                 "weight" => 2}
    ]

    weight=0
    why=""
    rules.each do | rule |
      case
        when rule["text"].present?
          if event["description"].include?(rule["text"]) || event["title"].include?(rule["text"])
            weight+=rule["weight"]
            why+="[#{rule["text"]}, #{rule["weight"]}]; "
          end
        when rule["where"].present?
          if event["venue"].present? && event["venue"]["title"].downcase.include?(rule["where"].downcase)
            weight+=rule["weight"]
            why+="[#{rule["where"]}, #{rule["weight"]}]; "
          end
        when rule["when"].present?
          if time_match(event, rule["when"])
            weight+=rule["weight"]
            why+="[#{rule["when"].to_s}, #{rule["weight"]}]; "
          end
      end
    end
    [rank_from_weight(weight), why]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/calaview_controller.rb
class CalaviewController < ApplicationController
  def index
    @threshold = params["threshold"].to_i || 1

    cal = CalagatorEvents.new
    @ranked_events = cal.ranked_events({})
    @selected_events = @ranked_events.select {|e| e['weighted_rank'] >= @threshold }

    Rails.logger.info "** Found #{@ranked_events.size} events, selected #{@selected_events.size}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    BlueCloth.new(text, :relaxed => true).to_html
  end

  # Return a HTML string with the BR tags converted to XHTML compliant markup.
  def upgrade_br(content)
    content.gsub('<br>','<br />')
  end
end

app/helpers/calaview_helper.rb
module CalaviewHelper
  def event_url(e_id)
    "http://calagator.org/events/#{e_id}"
  end

  MAX_DESCRIPTION = 80 * 5

  def format_description(string)
    if string.length > MAX_DESCRIPTION
      string = string[0..MAX_DESCRIPTION] + "... _(more)_"
    end
    sanitize(auto_link(upgrade_br(markdown(string))))
  end

  def format_when(event)
    start_time = DateTime.parse(event['start_time']).strftime("%I:%M%P")
    end_time = DateTime.parse(event['end_time']).strftime("%I:%M%P")
    start_date = DateTime.parse(event['start_time']).strftime("%b %e, %Y")

    "#{start_time} to #{end_time} on #{start_date}"
  end

  def format_where(venue)
    if venue.present? && venue['title'].present?
      "at #{venue['title']}"
    else
      ""
    end
  end

  def format_why(why)
    if why.present?
      "why: #{why}"
    else
      ""
    end
  end
end

app/views/calaview/_event.html.erb
<div class="event_title"><a href="<%=event_url(event['id'])%>"><%= event['title'] %></a> (Ranked: <%= event['weighted_rank']%>)</div>
<div class="event_when_where">
  <div class="event_when"><%= format_when(event) %></div>
  <div class="event_where"><%= format_where(event['venue'])%> </div>
  <div class="event_why"><%= format_why(event['why_rank']) %></div>
</div>
<div class="event_description"><%= format_description(event['description']) %></div>

app/views/calaview/index.html.erb
<h1>Events</h1>

<p>Displaying <%= @selected_events.size %> events of <%= @ranked_events.size %> total using threshold <%= @threshold %></p>

<%= render partial: "event", collection: @selected_events %>

<% if @selected_events.size < @ranked_events.size %>

<p><%= (@ranked_events.size - @selected_events.size) %> events below current threshold of <%= @threshold %>
  <%= link_to("See all events", calaview_path(:threshold => -9999999)) %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Liquididea</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>